_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "/data/nihcc/R-50.pkl" #"detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
    NUM_CLASSES: 1
OUTPUT_DIR: '/data/nihcc/UBT/LiTS/exp1'

SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (3180, 5088)
  MAX_ITER: 6360
  IMG_PER_BATCH_LABEL: 32
  IMG_PER_BATCH_UNLABEL: 32
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 636
  WARMUP_ITERS: 150
DATALOADER:
  SUP_PERCENT: 1.0
  RANDOM_DATA_SEED: 1
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("lesion_train",)
  TEST: ("lesion_train",)
SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 6000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0

TEST:
  EVAL_PERIOD: 10000
